# Managing Exception in Controllers with Active Record
- Not found
- DB operation issue

Previously we created a endpoint to delete, it had a issue:
- If we try to delete the resource for 2nd time, it threw an exception.

**Handelling exception: app/controllers/books_controller.rb**

```rb
class BooksConteoller < ApplicationController

    rescue_from ActiveRecord::RecordNotDestroyed, with: :not_destroyed
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    def destroy
        book = Book.find(params[:id]).destroy!
        head :no_content
    end

    def not_destroyed
      render json: {}, status: :unprocessable_entity
    end
  
    def not_found
      render json: {"error": "Resource not found"}, status: :not_found
    end    
end
```

In the following controller logic we've included two things to rescue us from:
- When object couldn't be deleted.
- When object itself is not found.

**Test:**

```
curl --request DELETE http://localhost:3000/books/2

{"error":"Resource not found"}
```

## PRO TIPS: Refactoring / Organizing Code

As we see our controller always inherits from **controllers/application_controller.rb** so instead of handelling
the exceptions here, we can handle it there:

```rb
class ApplicationController < ActionController::API

    rescue_from ActiveRecord::RecordNotDestroyed, with: :not_destroyed
    rescue_from ActiveRecord::RecordNotFound, with: :not_found

    private
  
    def not_destroyed
      render json: {}, status: :unprocessable_entity
    end
  
    def not_found
      render json: {"error": "Resource not found"}, status: :not_found
    end
end

```
